project_id = "jvfvwysvhqpiosvhzhkf"

[edge_runtime]
policy = "per_worker"

[functions.realtime-chat]
verify_jwt = false

[functions.simli-token]
verify_jwt = false

[functions.hume-tts-stream]
verify_jwt = false
